[Definition]
# Regex to match client IP (<HOST>) requesting forbidden paths returning 403, 404, or 444
failregex = ^<HOST> \- \- \[.*\] ".*(GET|POST|HEAD) .*(?i)(\.env|\.git|\.config|\.sql|\.yml|\.yaml|\.bak|setup\.php|wp-admin|phpmyadmin|administrator).* HTTP\/.*" (403|404|444) .*$

ignoreregex =
